### ISSUE TITLE
Not enrolling after payment

### ISSUE THREAD

**Issue by vkanyoze** [jayluxferro/Flutterwave-Moodle-Plugin#1]
After successful payment, it still shows you are not enrolled in this course

**Comment by jayluxferro** [comment]
Check how the course was setup or configured. Can you enable error display in your configuration? It'll be helpful if i can get an error log to determine what exactly went wrong. I have tested the plugin again and I haven't encountered the error you've mentioned. Please provide details by enabling error reporting in your `config.php` file.

**Comment by jayluxferro** [comment]
Hi, I've updated the plugin to fix the bug due to changes in Flutterwave's API. Kindly confirm.

**Comment by miykarl** [comment]
flutterwave enrollment failed after payment Moodle
